name: Mitgliederzahl aktualisieren

on:
  schedule:
    - cron: "0 6 * * *" # jeden Tag um 6 Uhr früh
  workflow_dispatch: # manuell auslösbar

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Repo klonen
        uses: actions/checkout@v4

      - name: Mitgliederzahl abrufen
        run: |
          curl -s https://dav-karlsbad.de/ > seite.html
          ZAHL=$(grep -oP 'Mitglieder der Sektion aktuell:\s*\K[0-9]+' seite.html | head -1)
          echo "{ \"mitglieder\": \"$ZAHL\" }" > mitglieder.json
          rm seite.html

      - name: Änderungen committen
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add mitglieder.json
          git commit -m "Mitgliederzahl aktualisiert" || echo "Keine Änderungen"
          git push
