name: Update DAV Members

on:
  schedule:
    - cron: "0 3 * * *"  # täglich 03:00 UTC
  workflow_dispatch:      # manuelles Auslösen möglich

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: npm run update

      - name: Commit and push result
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add members.json
          git commit -m "Update members.json" || echo "No changes"
          git push
